"""EC8 phase 8d — Payroll service (canonical gross-pay ledger engine).

Scope boundary (LOCKED — owner-approved EC8 preflight + Phase 8d gate):
This is an internal workforce gross-pay ledger — NOT a payroll-processing,
tax-filing, or banking service. No ACH, no direct deposit, no SSN/bank
storage, no tax withholding or statutory deductions, no W-2/1099
generation. Overtime math is a configurable internal estimate only — never
represented as legal/compliance payroll.

Architecture:
- `PayPeriod` — one per tenant per Saturday-Friday week (payday == end_date,
  always the Friday). Uniqueness enforced by a DB index on
  (tenant_id, start_date) — this is what structurally prevents overlapping
  periods (every lookup/creation normalizes through
  `week_bounds_for_date_str` first).
- `PayrollSnapshot` — one per (period, employee); a pure READ MODEL derived
  from the `PayrollTransaction` ledger (see `_sum_ledger`). Hours/rate are
  computed fresh on each recalculation while the period is open/review;
  money totals always equal a live sum over the ledger.
- `PayrollTransaction` — append-only ledger; the single source of truth.
  Corrections/voids never mutate a historical row's `amount_cents` — they
  add a new offsetting `type="void"` row and flip `voided=True` on the
  original (see `_void_transaction_row`).
- Financial status (`partially_paid` / `paid`) is NEVER set directly by an
  API caller — it is always derived from the ledger by
  `_refresh_period_financial_status`.
"""
from __future__ import annotations

from datetime import date, datetime, timedelta, timezone
from typing import Any, Optional

from ..core.db import db
from ..core.time_utils import prepare_for_mongo, serialize_doc, utc_now
from ..models.pay_period import PayPeriod
from ..models.payroll_snapshot import PayrollSnapshot
from ..models.payroll_transaction import PayrollTransaction
from .activity import record_activity_with_audit
from .time_period_utils import week_bounds_for_date_str

SYSTEM_ACTOR = "system"
SYSTEM_EMAIL = "system@signguy.internal"

# Ledger transaction types a manager may enter directly. `earning` /
# `overtime_earning` are only ever system-generated by recalculation.
# `carryover_in` / `carryover_out` are only ever system-generated by
# `close_period`. `correction` / `void` are reserved for the reversal
# machinery below.
MANUAL_TRANSACTION_TYPES = {"adjustment", "advance", "advance_repayment", "payment"}
# Types that may never be voided directly through the manual-void endpoint —
# `earning`/`overtime_earning` are only ever superseded by recalculation,
# and a `void` row can never itself be voided (no double-reversal).
NON_VOIDABLE_TYPES = {"earning", "overtime_earning", "void"}

DEFAULT_PAYROLL_SETTINGS: dict[str, Any] = {
    "overtime_enabled": True,
    "weekly_threshold_minutes": 2400,   # 40 hours
    "overtime_multiplier": 1.5,
    "rounding_policy": "nearest_cent",  # informational only — money is always integer cents
    "default_payday": "friday",         # LOCKED — v1 supports Friday payday only
    "work_week_start": "saturday",      # LOCKED — v1 supports Saturday-start weeks only
}


class PayrollError(Exception):
    def __init__(self, status_code: int, detail: str):
        self.status_code = status_code
        self.detail = detail
        super().__init__(detail)


# ---------------------------------------------------------------------------
# Payroll settings (existing Settings framework, "payroll" namespace)
# ---------------------------------------------------------------------------

async def get_payroll_settings(*, tenant_id: str) -> dict[str, Any]:
    from . import settings as settings_service
    stored = await settings_service.list_namespace(tenant_id=tenant_id, namespace="payroll")
    return {**DEFAULT_PAYROLL_SETTINGS, **stored}


async def update_payroll_settings(*, tenant_id: str, updates: dict[str, Any], updated_by: str) -> dict[str, Any]:
    from . import settings as settings_service
    allowed = set(DEFAULT_PAYROLL_SETTINGS.keys())
    clean: dict[str, Any] = {}
    for k, v in updates.items():
        if k not in allowed:
            raise PayrollError(400, f"Unknown payroll setting: {k}")
        if k == "default_payday" and v != "friday":
            raise PayrollError(400, "default_payday is locked to 'friday' in v1")
        if k == "work_week_start" and v != "saturday":
            raise PayrollError(400, "work_week_start is locked to 'saturday' in v1")
        if k == "weekly_threshold_minutes" and (not isinstance(v, (int, float)) or v <= 0):
            raise PayrollError(400, "weekly_threshold_minutes must be a positive number")
        if k == "overtime_multiplier" and (not isinstance(v, (int, float)) or v < 1.0):
            raise PayrollError(400, "overtime_multiplier must be >= 1.0")
        clean[k] = v
    if not clean:
        raise PayrollError(400, "No valid settings provided")
    await settings_service.set_many(tenant_id=tenant_id, namespace="payroll", values=clean, updated_by=updated_by)
    return await get_payroll_settings(tenant_id=tenant_id)


def _resolve_overtime_policy(tenant_settings: dict[str, Any], employee: dict[str, Any]) -> dict[str, Any]:
    override = employee.get("overtime_override")
    if isinstance(override, dict) and override:
        return {
            "enabled": bool(override.get("enabled", tenant_settings["overtime_enabled"])),
            "weekly_threshold_minutes": int(override.get("weekly_threshold_minutes", tenant_settings["weekly_threshold_minutes"])),
            "multiplier": float(override.get("multiplier", tenant_settings["overtime_multiplier"])),
            "source": "employee_override",
        }
    return {
        "enabled": bool(tenant_settings["overtime_enabled"]),
        "weekly_threshold_minutes": int(tenant_settings["weekly_threshold_minutes"]),
        "multiplier": float(tenant_settings["overtime_multiplier"]),
        "source": "tenant_default",
    }


# ---------------------------------------------------------------------------
# Pay Period
# ---------------------------------------------------------------------------

async def _get_period(tenant_id: str, period_id: str) -> dict:
    doc = await db.pay_periods.find_one({"id": period_id, "tenant_id": tenant_id}, {"_id": 0})
    if not doc:
        raise PayrollError(404, "Pay Period not found")
    return doc


async def get_or_create_pay_period(*, tenant_id: str, period_start: str, actor_user_id: str) -> dict:
    week_start, week_end = week_bounds_for_date_str(period_start)
    existing = await db.pay_periods.find_one({"tenant_id": tenant_id, "start_date": week_start}, {"_id": 0})
    if existing:
        await _link_pending_carryovers(tenant_id, existing, actor_user_id)
        doc = await db.pay_periods.find_one({"id": existing["id"], "tenant_id": tenant_id}, {"_id": 0})
        return serialize_doc(doc or {})
    doc = PayPeriod(
        tenant_id=tenant_id, start_date=week_start, end_date=week_end, payday=week_end,
        created_by=actor_user_id, updated_by=actor_user_id,
    ).model_dump()
    await db.pay_periods.insert_one(prepare_for_mongo(dict(doc)))
    doc.pop("_id", None)
    await _link_pending_carryovers(tenant_id, doc, actor_user_id)
    refreshed = await db.pay_periods.find_one({"id": doc["id"], "tenant_id": tenant_id}, {"_id": 0})
    return serialize_doc(refreshed or doc)


async def _period_summary(tenant_id: str, period_id: str) -> dict:
    snaps = await list_period_snapshots(tenant_id=tenant_id, period_id=period_id)
    return {
        "employee_count": len(snaps),
        "total_gross_cents": sum(s["gross_regular_cents"] + s["gross_overtime_cents"] for s in snaps),
        "total_paid_cents": sum(s["total_paid_cents"] for s in snaps),
        "total_remaining_cents": sum(s["remaining_balance_cents"] for s in snaps),
        "blocking_warning_count": sum(1 for s in snaps if s.get("warnings")),
    }


async def list_pay_periods(*, tenant_id: str, status: Optional[str] = None, limit: int = 200) -> list[dict]:
    filt: dict[str, Any] = {"tenant_id": tenant_id}
    if status:
        filt["status"] = status
    cur = db.pay_periods.find(filt, {"_id": 0}).sort("start_date", -1).limit(limit)
    periods = [serialize_doc(d) async for d in cur]
    for p in periods:
        p["summary"] = await _period_summary(tenant_id, p["id"])
    return periods


async def get_pay_period_detail(*, tenant_id: str, period_id: str) -> dict:
    period = await _get_period(tenant_id, period_id)
    snapshots = await list_period_snapshots(tenant_id=tenant_id, period_id=period_id)
    return {"period": serialize_doc(period), "snapshots": snapshots, "summary": await _period_summary(tenant_id, period_id)}


# ---------------------------------------------------------------------------
# Snapshot recalculation (idempotent — never duplicates generated earnings)
# ---------------------------------------------------------------------------

async def list_period_snapshots(*, tenant_id: str, period_id: str) -> list[dict]:
    cur = db.payroll_snapshots.find({"tenant_id": tenant_id, "pay_period_id": period_id}, {"_id": 0}).sort("employee_name", 1)
    return [serialize_doc(d) async for d in cur]


def _overlaps(a_start: str, a_end: Optional[str], b_start: str, b_end: Optional[str]) -> bool:
    a_end_dt = datetime.fromisoformat(a_end) if a_end else datetime.now(timezone.utc)
    b_end_dt = datetime.fromisoformat(b_end) if b_end else datetime.now(timezone.utc)
    return datetime.fromisoformat(a_start) < b_end_dt and datetime.fromisoformat(b_start) < a_end_dt


async def _collect_employee_warnings(tenant_id: str, employee: dict, timesheet: dict) -> list[str]:
    warnings: list[str] = []
    if int(employee.get("hourly_rate_cents", 0) or 0) <= 0:
        warnings.append("missing_rate: Employee hourly rate is not set")
    if timesheet.get("status") != "approved":
        warnings.append("timesheet_not_approved: Weekly timesheet has not been approved yet")
    if timesheet.get("incomplete_entry_count", 0) > 0:
        warnings.append(f"open_time_entries: {timesheet['incomplete_entry_count']} time entry(ies) are missing a clock-out")
    entries = [e async for e in db.time_entries.find(
        {"tenant_id": tenant_id, "employee_id": employee["id"], "work_date": {"$gte": timesheet["week_start"], "$lte": timesheet["week_end"]},
         "status": {"$ne": "voided"}}, {"_id": 0, "clock_in_at": 1, "clock_out_at": 1},
    ).sort("clock_in_at", 1)]
    for i in range(len(entries) - 1):
        if _overlaps(entries[i]["clock_in_at"], entries[i].get("clock_out_at"), entries[i + 1]["clock_in_at"], entries[i + 1].get("clock_out_at")):
            warnings.append("overlapping_entries: Two or more time entries overlap for this employee this week")
            break
    return warnings


async def _sum_ledger(tenant_id: str, employee_id: str, period_id: str) -> dict[str, int]:
    sums: dict[str, int] = {}
    pipeline = [
        {"$match": {"tenant_id": tenant_id, "employee_id": employee_id, "pay_period_id": period_id,
                     "voided": False, "type": {"$ne": "void"}}},
        {"$group": {"_id": "$type", "total": {"$sum": "$amount_cents"}}},
    ]
    async for row in db.payroll_transactions.aggregate(pipeline):
        sums[row["_id"]] = int(row["total"])
    return sums


def _money_totals(sums: dict[str, int]) -> dict[str, int]:
    gross_regular = sums.get("earning", 0)
    gross_overtime = sums.get("overtime_earning", 0)
    adjustment = sums.get("adjustment", 0) + sums.get("correction", 0)
    advance = sums.get("advance", 0)
    repayment = sums.get("advance_repayment", 0)
    payment = sums.get("payment", 0)
    carryover_in = sums.get("carryover_in", 0)
    carryover_out = sums.get("carryover_out", 0)
    total_earned = gross_regular + gross_overtime + adjustment + carryover_in - repayment
    total_paid = advance + payment
    remaining = total_earned - total_paid - carryover_out
    return {
        "gross_regular_cents": gross_regular, "gross_overtime_cents": gross_overtime,
        "adjustment_total_cents": adjustment, "advance_total_cents": advance,
        "repayment_total_cents": repayment, "payment_total_cents": payment,
        "carryover_in_cents": carryover_in, "carryover_out_cents": carryover_out,
        "total_earned_cents": total_earned, "total_paid_cents": total_paid,
        "remaining_balance_cents": remaining,
    }


async def recompute_snapshot_totals(*, tenant_id: str, period_id: str, employee_id: str) -> dict:
    """Re-derive a snapshot's MONEY fields from the ledger only (hours/rate untouched).
    Creates a minimal snapshot row if one doesn't exist yet (e.g. an advance
    recorded before the first recalculation)."""
    sums = await _sum_ledger(tenant_id, employee_id, period_id)
    totals = _money_totals(sums)
    existing = await db.payroll_snapshots.find_one({"tenant_id": tenant_id, "pay_period_id": period_id, "employee_id": employee_id}, {"_id": 0})
    now_iso = utc_now().isoformat()
    if existing:
        await db.payroll_snapshots.update_one(
            {"id": existing["id"], "tenant_id": tenant_id},
            {"$set": {**totals, "updated_at": now_iso}},
        )
    else:
        emp = await db.employees.find_one({"id": employee_id, "tenant_id": tenant_id}, {"_id": 0})
        if not emp:
            raise PayrollError(404, "Employee not found")
        doc = PayrollSnapshot(
            tenant_id=tenant_id, pay_period_id=period_id, employee_id=employee_id, employee_name=emp["name"],
            employee_status=emp["status"], linked_user_id=emp.get("linked_user_id"),
            hourly_rate_cents=emp.get("hourly_rate_cents", 0), **totals,
            created_by=SYSTEM_ACTOR, updated_by=SYSTEM_ACTOR,
        ).model_dump()
        await db.payroll_snapshots.insert_one(prepare_for_mongo(dict(doc)))
    doc = await db.payroll_snapshots.find_one({"tenant_id": tenant_id, "pay_period_id": period_id, "employee_id": employee_id}, {"_id": 0})
    await _refresh_period_financial_status(tenant_id, period_id)
    return serialize_doc(doc or {})


async def _replace_generated_transaction(tenant_id: str, employee_id: str, period: dict, txn_type: str,
                                          new_amount_cents: int, timesheet_id: str) -> None:
    """Idempotent regeneration: only void + recreate when the computed amount
    actually changed. Clicking Recalculate repeatedly with unchanged hours
    never creates duplicate ledger rows."""
    existing = await db.payroll_transactions.find_one(
        {"tenant_id": tenant_id, "employee_id": employee_id, "pay_period_id": period["id"], "type": txn_type, "voided": False},
        {"_id": 0},
    )
    if existing and existing["amount_cents"] == new_amount_cents:
        return
    now_iso = utc_now().isoformat()
    if existing:
        await db.payroll_transactions.update_one(
            {"id": existing["id"], "tenant_id": tenant_id},
            {"$set": {"voided": True, "voided_by": SYSTEM_ACTOR, "voided_at": now_iso, "void_reason": "superseded_by_recalculation"}},
        )
    if new_amount_cents > 0:
        doc = PayrollTransaction(
            tenant_id=tenant_id, employee_id=employee_id, pay_period_id=period["id"], type=txn_type,
            amount_cents=new_amount_cents, effective_date=period["end_date"],
            reference=f"{'Regular' if txn_type == 'earning' else 'Overtime'} pay {period['start_date']}\u2013{period['end_date']}",
            source_record_type="timesheet", source_record_id=timesheet_id, created_by=SYSTEM_ACTOR,
        ).model_dump()
        await db.payroll_transactions.insert_one(prepare_for_mongo(dict(doc)))


async def recalc_employee_snapshot(*, tenant_id: str, period: dict, employee_id: str) -> dict:
    if period["status"] not in ("open", "review"):
        raise PayrollError(409, f"Pay Period is {period['status']} — reopen it before recalculating")
    emp = await db.employees.find_one({"id": employee_id, "tenant_id": tenant_id}, {"_id": 0})
    if not emp:
        raise PayrollError(404, "Employee not found")
    from . import timesheet_service
    ts = await timesheet_service.get_or_create_weekly_timesheet(tenant_id=tenant_id, employee_id=employee_id, week_start=period["start_date"])
    tenant_settings = await get_payroll_settings(tenant_id=tenant_id)
    ot_policy = _resolve_overtime_policy(tenant_settings, emp)
    worked_minutes = ts["worked_minutes"]
    if ot_policy["enabled"]:
        threshold = ot_policy["weekly_threshold_minutes"]
        regular_minutes = min(worked_minutes, threshold)
        overtime_minutes = max(worked_minutes - threshold, 0)
    else:
        regular_minutes, overtime_minutes = worked_minutes, 0
    rate = int(emp.get("hourly_rate_cents", 0) or 0)
    gross_regular_cents = round(regular_minutes / 60 * rate)
    gross_overtime_cents = round(overtime_minutes / 60 * rate * ot_policy["multiplier"])
    warnings = await _collect_employee_warnings(tenant_id, emp, ts)

    await _replace_generated_transaction(tenant_id, employee_id, period, "earning", gross_regular_cents, ts["id"])
    await _replace_generated_transaction(tenant_id, employee_id, period, "overtime_earning", gross_overtime_cents, ts["id"])

    sums = await _sum_ledger(tenant_id, employee_id, period["id"])
    totals = _money_totals(sums)
    existing = await db.payroll_snapshots.find_one({"tenant_id": tenant_id, "pay_period_id": period["id"], "employee_id": employee_id}, {"_id": 0})
    now_iso = utc_now().isoformat()
    fields = {
        "employee_name": emp["name"], "employee_status": emp["status"], "linked_user_id": emp.get("linked_user_id"),
        "hourly_rate_cents": rate, "overtime_policy_snapshot": ot_policy,
        "regular_minutes": regular_minutes, "overtime_minutes": overtime_minutes,
        **totals, "calculated_at": now_iso, "source_timesheet_ids": [ts["id"]], "warnings": warnings,
        "locked": False, "updated_at": now_iso, "updated_by": SYSTEM_ACTOR,
    }
    if existing:
        await db.payroll_snapshots.update_one(
            {"id": existing["id"], "tenant_id": tenant_id},
            {"$set": fields, "$inc": {"calculation_version": 1}},
        )
    else:
        doc = PayrollSnapshot(tenant_id=tenant_id, pay_period_id=period["id"], employee_id=employee_id,
                               calculation_version=1, created_by=SYSTEM_ACTOR, **fields).model_dump()
        await db.payroll_snapshots.insert_one(prepare_for_mongo(dict(doc)))
    doc = await db.payroll_snapshots.find_one({"tenant_id": tenant_id, "pay_period_id": period["id"], "employee_id": employee_id}, {"_id": 0})
    await _refresh_period_financial_status(tenant_id, period["id"])
    return serialize_doc(doc or {})


async def _candidate_employee_ids(tenant_id: str, period: dict) -> set[str]:
    ids: set[str] = set()
    async for t in db.timesheets.find({"tenant_id": tenant_id, "week_start": period["start_date"]}, {"_id": 0, "employee_id": 1}):
        ids.add(t["employee_id"])
    async for s in db.payroll_snapshots.find({"tenant_id": tenant_id, "pay_period_id": period["id"]}, {"_id": 0, "employee_id": 1}):
        ids.add(s["employee_id"])
    async for tx in db.payroll_transactions.find({"tenant_id": tenant_id, "pay_period_id": period["id"], "voided": False}, {"_id": 0, "employee_id": 1}):
        ids.add(tx["employee_id"])
    return ids


async def recalc_period(*, tenant_id: str, period_id: str, actor_user_id: str, actor_email: str) -> dict:
    period = await _get_period(tenant_id, period_id)
    if period["status"] not in ("open", "review"):
        raise PayrollError(409, f"Pay Period is {period['status']} — reopen it before recalculating")
    employee_ids = await _candidate_employee_ids(tenant_id, period)
    for emp_id in employee_ids:
        await recalc_employee_snapshot(tenant_id=tenant_id, period=period, employee_id=emp_id)
    await record_activity_with_audit(
        tenant_id=tenant_id, actor_user_id=actor_user_id, actor_email=actor_email,
        module="team", action="payroll.period_recalculated", entity_type="pay_period", entity_id=period_id,
        summary=f"Pay Period {period['start_date']}\u2013{period['end_date']} recalculated ({len(employee_ids)} employee(s))",
    )
    return await get_pay_period_detail(tenant_id=tenant_id, period_id=period_id)


# ---------------------------------------------------------------------------
# Blocking warnings gate (approve / close)
# ---------------------------------------------------------------------------

async def _collect_blocking_warnings(tenant_id: str, period: dict) -> list[dict]:
    blocking: list[dict] = []
    snapshots = await list_period_snapshots(tenant_id=tenant_id, period_id=period["id"])
    snapshotted_ids = {s["employee_id"] for s in snapshots}
    for s in snapshots:
        if s.get("warnings"):
            blocking.append({"employee_id": s["employee_id"], "employee_name": s["employee_name"], "warnings": s["warnings"]})
    async for t in db.timesheets.find({"tenant_id": tenant_id, "week_start": period["start_date"]}, {"_id": 0, "employee_id": 1}):
        if t["employee_id"] not in snapshotted_ids:
            emp = await db.employees.find_one({"id": t["employee_id"], "tenant_id": tenant_id}, {"_id": 0, "name": 1})
            blocking.append({"employee_id": t["employee_id"], "employee_name": (emp or {}).get("name", t["employee_id"]),
                              "warnings": ["not_recalculated: Employee has hours logged this week but has not been included in a Recalculate yet"]})
    return blocking


# ---------------------------------------------------------------------------
# Approve / Reopen / Close / Void
# ---------------------------------------------------------------------------

async def approve_period(*, tenant_id: str, period_id: str, actor_user_id: str, actor_email: str,
                          override_reason: Optional[str] = None) -> dict:
    period = await _get_period(tenant_id, period_id)
    if period["status"] not in ("open", "review"):
        raise PayrollError(409, f"Cannot approve a Pay Period that is {period['status']}")
    blocking = await _collect_blocking_warnings(tenant_id, period)
    if blocking and not (override_reason and override_reason.strip()):
        raise PayrollError(409, f"blocking_warnings: {len(blocking)} employee(s) have unresolved warnings — an override reason is required to approve anyway")
    now_iso = utc_now().isoformat()
    history = period.get("status_history", []) + [{"from": period["status"], "to": "approved", "reason": override_reason, "actor_user_id": actor_user_id, "at": now_iso}]
    await db.payroll_snapshots.update_many({"tenant_id": tenant_id, "pay_period_id": period_id}, {"$set": {"locked": True, "updated_at": now_iso}})
    await db.pay_periods.update_one(
        {"id": period_id, "tenant_id": tenant_id},
        {"$set": {"status": "approved", "lock_state": "locked", "approved_by": actor_user_id, "approved_at": now_iso,
                   "status_history": history, "updated_by": actor_user_id, "updated_at": now_iso}},
    )
    await record_activity_with_audit(
        tenant_id=tenant_id, actor_user_id=actor_user_id, actor_email=actor_email,
        module="team", action="payroll.period_approved", entity_type="pay_period", entity_id=period_id,
        summary=f"Pay Period {period['start_date']}\u2013{period['end_date']} approved" + (f" (override: {override_reason})" if override_reason else ""),
        severity="warning" if override_reason else "info",
        diff={"blocking_warnings": blocking, "override_reason": override_reason},
    )
    return await get_pay_period_detail(tenant_id=tenant_id, period_id=period_id)


async def reopen_period(*, tenant_id: str, period_id: str, actor_user_id: str, actor_email: str, reason: str) -> dict:
    if not reason or not reason.strip():
        raise PayrollError(400, "A reason is required to reopen a Pay Period")
    period = await _get_period(tenant_id, period_id)
    if period["status"] not in ("approved", "partially_paid", "paid"):
        raise PayrollError(409, f"Cannot reopen a Pay Period that is {period['status']}")
    now_iso = utc_now().isoformat()
    history = period.get("status_history", []) + [{"from": period["status"], "to": "open", "reason": reason, "actor_user_id": actor_user_id, "at": now_iso}]
    await db.payroll_snapshots.update_many({"tenant_id": tenant_id, "pay_period_id": period_id}, {"$set": {"locked": False, "updated_at": now_iso}})
    await db.pay_periods.update_one(
        {"id": period_id, "tenant_id": tenant_id},
        {"$set": {"status": "open", "lock_state": "unlocked", "status_history": history, "updated_by": actor_user_id, "updated_at": now_iso}},
    )
    await record_activity_with_audit(
        tenant_id=tenant_id, actor_user_id=actor_user_id, actor_email=actor_email,
        module="team", action="payroll.period_reopened", entity_type="pay_period", entity_id=period_id,
        summary=f"Pay Period {period['start_date']}\u2013{period['end_date']} reopened: {reason}", severity="warning",
    )
    return await get_pay_period_detail(tenant_id=tenant_id, period_id=period_id)


async def _create_carryover_in(tenant_id: str, target_period: dict, employee_id: str, amount_cents: int, source_transaction_id: str) -> None:
    idem_in = f"carryover_in:{source_transaction_id}"
    existing = await db.payroll_transactions.find_one({"tenant_id": tenant_id, "idempotency_key": idem_in, "voided": False}, {"_id": 0})
    if existing:
        return
    doc = PayrollTransaction(
        tenant_id=tenant_id, employee_id=employee_id, pay_period_id=target_period["id"], type="carryover_in",
        amount_cents=amount_cents, effective_date=target_period["start_date"], reference="Carried from prior Pay Period",
        source_record_type="payroll_transaction", source_record_id=source_transaction_id,
        carryover_link_id=source_transaction_id, idempotency_key=idem_in, created_by=SYSTEM_ACTOR,
    ).model_dump()
    await db.payroll_transactions.insert_one(prepare_for_mongo(dict(doc)))
    await recompute_snapshot_totals(tenant_id=tenant_id, period_id=target_period["id"], employee_id=employee_id)


async def _link_pending_carryovers(tenant_id: str, new_period: dict, actor_user_id: str) -> None:
    pending = [p async for p in db.payroll_carryovers.find(
        {"tenant_id": tenant_id, "linked": False, "source_period_end_date_plus_one": new_period["start_date"]}, {"_id": 0},
    )]
    for p in pending:
        await _create_carryover_in(tenant_id, new_period, p["employee_id"], p["amount_cents"], p["source_transaction_id"])
        await db.payroll_carryovers.update_one(
            {"id": p["id"], "tenant_id": tenant_id},
            {"$set": {"linked": True, "target_period_id": new_period["id"], "linked_at": utc_now().isoformat()}},
        )
        await record_activity_with_audit(
            tenant_id=tenant_id, actor_user_id=actor_user_id, actor_email=SYSTEM_EMAIL,
            module="team", action="payroll.carryover_linked", entity_type="pay_period", entity_id=new_period["id"],
            summary=f"Pending carryover of {p['amount_cents']} cents linked from Pay Period {p['source_period_id']}",
        )


async def _carry_over_snapshot(tenant_id: str, period: dict, snapshot: dict) -> None:
    amount = snapshot["remaining_balance_cents"]
    if amount <= 0:
        return
    idem_out = f"carryover_out:{period['id']}:{snapshot['employee_id']}"
    existing_out = await db.payroll_transactions.find_one({"tenant_id": tenant_id, "idempotency_key": idem_out, "voided": False}, {"_id": 0})
    if existing_out:
        return
    out_doc = PayrollTransaction(
        tenant_id=tenant_id, employee_id=snapshot["employee_id"], pay_period_id=period["id"], type="carryover_out",
        amount_cents=amount, effective_date=period["end_date"], reference="Carried to next Pay Period",
        idempotency_key=idem_out, created_by=SYSTEM_ACTOR,
    ).model_dump()
    await db.payroll_transactions.insert_one(prepare_for_mongo(dict(out_doc)))
    next_start = (date.fromisoformat(period["end_date"]) + timedelta(days=1)).isoformat()
    next_period = await db.pay_periods.find_one({"tenant_id": tenant_id, "start_date": next_start}, {"_id": 0})
    if next_period:
        await _create_carryover_in(tenant_id, next_period, snapshot["employee_id"], amount, out_doc["id"])
    else:
        existing_pending = await db.payroll_carryovers.find_one(
            {"tenant_id": tenant_id, "employee_id": snapshot["employee_id"], "source_period_id": period["id"], "linked": False}, {"_id": 0},
        )
        if not existing_pending:
            import uuid
            await db.payroll_carryovers.insert_one(prepare_for_mongo({
                "id": str(uuid.uuid4()), "tenant_id": tenant_id, "employee_id": snapshot["employee_id"],
                "source_period_id": period["id"], "source_period_end_date_plus_one": next_start,
                "source_transaction_id": out_doc["id"], "amount_cents": amount, "linked": False,
                "target_period_id": None, "created_at": utc_now(), "updated_at": utc_now(),
            }))
    await recompute_snapshot_totals(tenant_id=tenant_id, period_id=period["id"], employee_id=snapshot["employee_id"])


async def close_period(*, tenant_id: str, period_id: str, actor_user_id: str, actor_email: str,
                        override_reason: Optional[str] = None) -> dict:
    period = await _get_period(tenant_id, period_id)
    if period["status"] == "closed":
        raise PayrollError(400, "Pay Period is already closed")
    if period["status"] == "voided":
        raise PayrollError(409, "Cannot close a voided Pay Period")
    if period["status"] in ("open", "review"):
        raise PayrollError(409, "Pay Period must be approved before it can be closed")
    blocking = await _collect_blocking_warnings(tenant_id, period)
    snapshots = await list_period_snapshots(tenant_id=tenant_id, period_id=period_id)
    total_remaining = sum(s["remaining_balance_cents"] for s in snapshots)
    if (blocking or total_remaining > 0) and not (override_reason and override_reason.strip()):
        raise PayrollError(409, f"blocking_warnings_or_unpaid_balance: {len(blocking)} warning(s), {total_remaining} cents unpaid — an override reason is required to close anyway")
    for s in snapshots:
        if s["remaining_balance_cents"] > 0:
            await _carry_over_snapshot(tenant_id, period, s)
    now_iso = utc_now().isoformat()
    history = period.get("status_history", []) + [{"from": period["status"], "to": "closed", "reason": override_reason, "actor_user_id": actor_user_id, "at": now_iso}]
    await db.pay_periods.update_one(
        {"id": period_id, "tenant_id": tenant_id},
        {"$set": {"status": "closed", "closed_by": actor_user_id, "closed_at": now_iso,
                   "status_history": history, "updated_by": actor_user_id, "updated_at": now_iso}},
    )
    await record_activity_with_audit(
        tenant_id=tenant_id, actor_user_id=actor_user_id, actor_email=actor_email,
        module="team", action="payroll.period_closed", entity_type="pay_period", entity_id=period_id,
        summary=f"Pay Period {period['start_date']}\u2013{period['end_date']} closed" + (f" (override: {override_reason})" if override_reason else ""),
        severity="warning" if (override_reason or total_remaining > 0) else "info",
        diff={"blocking_warnings": blocking, "total_carried_forward_cents": total_remaining, "override_reason": override_reason},
    )
    return await get_pay_period_detail(tenant_id=tenant_id, period_id=period_id)


async def void_period(*, tenant_id: str, period_id: str, actor_user_id: str, actor_email: str, reason: str) -> dict:
    if not reason or not reason.strip():
        raise PayrollError(400, "A reason is required to void a Pay Period")
    period = await _get_period(tenant_id, period_id)
    if period["status"] == "closed":
        raise PayrollError(409, "Cannot void a closed Pay Period")
    if period["status"] == "voided":
        raise PayrollError(400, "Pay Period is already voided")
    now_iso = utc_now().isoformat()
    txns = [t async for t in db.payroll_transactions.find(
        {"tenant_id": tenant_id, "pay_period_id": period_id, "voided": False, "type": {"$ne": "void"}}, {"_id": 0},
    )]
    employee_ids: set[str] = set()
    for t in txns:
        employee_ids.add(t["employee_id"])
        reversal = PayrollTransaction(
            tenant_id=tenant_id, employee_id=t["employee_id"], pay_period_id=period_id, type="void",
            amount_cents=-t["amount_cents"], effective_date=now_iso[:10],
            source_record_type="payroll_transaction", source_record_id=t["id"],
            notes=f"Pay Period voided: {reason}", created_by=actor_user_id,
        ).model_dump()
        await db.payroll_transactions.insert_one(prepare_for_mongo(dict(reversal)))
        await db.payroll_transactions.update_one(
            {"id": t["id"], "tenant_id": tenant_id},
            {"$set": {"voided": True, "voided_by": actor_user_id, "voided_at": now_iso, "void_reason": f"Pay Period voided: {reason}"}},
        )
    for emp_id in employee_ids:
        await recompute_snapshot_totals(tenant_id=tenant_id, period_id=period_id, employee_id=emp_id)
    await db.payroll_snapshots.update_many({"tenant_id": tenant_id, "pay_period_id": period_id}, {"$set": {"locked": True, "updated_at": now_iso}})
    history = period.get("status_history", []) + [{"from": period["status"], "to": "voided", "reason": reason, "actor_user_id": actor_user_id, "at": now_iso}]
    await db.pay_periods.update_one(
        {"id": period_id, "tenant_id": tenant_id},
        {"$set": {"status": "voided", "lock_state": "locked", "voided_by": actor_user_id, "voided_at": now_iso,
                   "void_reason": reason, "status_history": history, "updated_by": actor_user_id, "updated_at": now_iso}},
    )
    await record_activity_with_audit(
        tenant_id=tenant_id, actor_user_id=actor_user_id, actor_email=actor_email,
        module="team", action="payroll.period_voided", entity_type="pay_period", entity_id=period_id,
        summary=f"Pay Period {period['start_date']}\u2013{period['end_date']} voided: {reason}", severity="warning",
    )
    return await get_pay_period_detail(tenant_id=tenant_id, period_id=period_id)


async def _refresh_period_financial_status(tenant_id: str, period_id: str) -> None:
    period = await db.pay_periods.find_one({"id": period_id, "tenant_id": tenant_id}, {"_id": 0})
    if not period or period["status"] not in ("approved", "partially_paid", "paid"):
        return
    snapshots = await list_period_snapshots(tenant_id=tenant_id, period_id=period_id)
    if not snapshots:
        return
    total_remaining = sum(s["remaining_balance_cents"] for s in snapshots)
    total_paid_activity = sum(s["advance_total_cents"] + s["payment_total_cents"] for s in snapshots)
    total_earned_activity = sum(s["total_earned_cents"] for s in snapshots)
    if total_earned_activity <= 0:
        # Nothing was ever owed this period (e.g. zero logged hours) — there is
        # no balance to "satisfy", so this must not be reported as paid/settled.
        new_status = "approved"
    elif total_remaining <= 0:
        new_status = "paid"
    elif total_paid_activity > 0:
        new_status = "partially_paid"
    else:
        new_status = "approved"
    if new_status == period["status"]:
        return
    now_iso = utc_now().isoformat()
    history = period.get("status_history", []) + [{"from": period["status"], "to": new_status, "reason": "derived_from_ledger", "actor_user_id": SYSTEM_ACTOR, "at": now_iso}]
    await db.pay_periods.update_one(
        {"id": period_id, "tenant_id": tenant_id},
        {"$set": {"status": new_status, "status_history": history, "updated_at": now_iso}},
    )
    await record_activity_with_audit(
        tenant_id=tenant_id, actor_user_id=SYSTEM_ACTOR, actor_email=SYSTEM_EMAIL,
        module="team", action="payroll.period_status_derived", entity_type="pay_period", entity_id=period_id,
        summary=f"Pay Period {period['start_date']}\u2013{period['end_date']} status derived: {period['status']} \u2192 {new_status}",
    )


# ---------------------------------------------------------------------------
# Ledger transactions (manual entry — advances / payments / adjustments)
# ---------------------------------------------------------------------------

async def add_manual_transaction(*, tenant_id: str, pay_period_id: str, employee_id: str, type: str,
                                  amount_cents: int, effective_date: str, actor_user_id: str, actor_email: str,
                                  reference: Optional[str] = None, notes: Optional[str] = None,
                                  payment_method: Optional[str] = None, payment_date: Optional[str] = None,
                                  idempotency_key: Optional[str] = None) -> dict:
    if type not in MANUAL_TRANSACTION_TYPES:
        raise PayrollError(400, f"type must be one of {sorted(MANUAL_TRANSACTION_TYPES)}")
    if not amount_cents or int(amount_cents) == 0:
        raise PayrollError(400, "amount_cents must be non-zero")
    period = await _get_period(tenant_id, pay_period_id)
    if period["status"] in ("closed", "voided"):
        raise PayrollError(409, f"Pay Period is {period['status']} — cannot add transactions")
    emp = await db.employees.find_one({"id": employee_id, "tenant_id": tenant_id}, {"_id": 0, "name": 1})
    if not emp:
        raise PayrollError(404, "Employee not found")
    if idempotency_key:
        existing = await db.payroll_transactions.find_one({"tenant_id": tenant_id, "idempotency_key": idempotency_key, "voided": False}, {"_id": 0})
        if existing:
            return serialize_doc(existing)
    doc = PayrollTransaction(
        tenant_id=tenant_id, employee_id=employee_id, pay_period_id=pay_period_id, type=type,
        amount_cents=int(amount_cents), effective_date=effective_date, reference=reference, notes=notes,
        payment_method=payment_method, payment_date=payment_date, idempotency_key=idempotency_key,
        created_by=actor_user_id,
    ).model_dump()
    await db.payroll_transactions.insert_one(prepare_for_mongo(dict(doc)))
    await recompute_snapshot_totals(tenant_id=tenant_id, period_id=pay_period_id, employee_id=employee_id)
    await record_activity_with_audit(
        tenant_id=tenant_id, actor_user_id=actor_user_id, actor_email=actor_email,
        module="team", action=f"payroll.transaction_{type}", entity_type="payroll_transaction", entity_id=doc["id"],
        summary=f"{type.replace('_', ' ').title()} of {amount_cents} cents recorded for {emp['name']}",
        severity="warning" if type in ("advance", "advance_repayment") else "info",
    )
    created = await db.payroll_transactions.find_one({"id": doc["id"], "tenant_id": tenant_id}, {"_id": 0})
    return serialize_doc(created or doc)


async def void_manual_transaction(*, tenant_id: str, transaction_id: str, actor_user_id: str, actor_email: str, reason: str) -> dict:
    if not reason or not reason.strip():
        raise PayrollError(400, "A reason is required to void a transaction")
    txn = await db.payroll_transactions.find_one({"id": transaction_id, "tenant_id": tenant_id}, {"_id": 0})
    if not txn:
        raise PayrollError(404, "Transaction not found")
    if txn["type"] in NON_VOIDABLE_TYPES:
        raise PayrollError(400, f"{txn['type']} transactions cannot be voided directly")
    if txn.get("voided"):
        raise PayrollError(400, "Transaction is already voided")
    period = await _get_period(tenant_id, txn["pay_period_id"])
    if period["status"] == "closed":
        raise PayrollError(409, "Cannot void a transaction in a closed Pay Period")
    now_iso = utc_now().isoformat()
    reversal = PayrollTransaction(
        tenant_id=tenant_id, employee_id=txn["employee_id"], pay_period_id=txn["pay_period_id"], type="void",
        amount_cents=-txn["amount_cents"], effective_date=now_iso[:10],
        source_record_type="payroll_transaction", source_record_id=txn["id"], notes=reason, created_by=actor_user_id,
    ).model_dump()
    await db.payroll_transactions.insert_one(prepare_for_mongo(dict(reversal)))
    await db.payroll_transactions.update_one(
        {"id": transaction_id, "tenant_id": tenant_id},
        {"$set": {"voided": True, "voided_by": actor_user_id, "voided_at": now_iso, "void_reason": reason}},
    )
    await recompute_snapshot_totals(tenant_id=tenant_id, period_id=txn["pay_period_id"], employee_id=txn["employee_id"])
    await record_activity_with_audit(
        tenant_id=tenant_id, actor_user_id=actor_user_id, actor_email=actor_email,
        module="team", action="payroll.transaction_voided", entity_type="payroll_transaction", entity_id=transaction_id,
        summary=f"Transaction voided: {reason}", severity="warning",
    )
    return await recompute_snapshot_totals(tenant_id=tenant_id, period_id=txn["pay_period_id"], employee_id=txn["employee_id"])


async def list_transactions(*, tenant_id: str, employee_id: Optional[str] = None, pay_period_id: Optional[str] = None,
                             include_voided: bool = False, limit: int = 500) -> list[dict]:
    filt: dict[str, Any] = {"tenant_id": tenant_id}
    if employee_id:
        filt["employee_id"] = employee_id
    if pay_period_id:
        filt["pay_period_id"] = pay_period_id
    if not include_voided:
        filt["voided"] = False
    cur = db.payroll_transactions.find(filt, {"_id": 0}).sort([("effective_date", -1), ("created_at", -1)]).limit(limit)
    return [serialize_doc(d) async for d in cur]


async def list_employee_snapshots(*, tenant_id: str, employee_id: str, limit: int = 200) -> list[dict]:
    cur = db.payroll_snapshots.find({"tenant_id": tenant_id, "employee_id": employee_id}, {"_id": 0}).limit(limit)
    snaps = [serialize_doc(d) async for d in cur]
    period_ids = list({s["pay_period_id"] for s in snaps})
    periods = {p["id"]: p async for p in db.pay_periods.find({"tenant_id": tenant_id, "id": {"$in": period_ids}}, {"_id": 0})}
    for s in snaps:
        p = periods.get(s["pay_period_id"], {})
        s["period_start"] = p.get("start_date")
        s["period_end"] = p.get("end_date")
        s["payday"] = p.get("payday")
        s["period_status"] = p.get("status")
    snaps.sort(key=lambda s: s.get("period_start") or "", reverse=True)
    return snaps
