"""Compatibility surface for Webstore branding workflows."""
from __future__ import annotations

from .webstore_branding_contracts import (
    ALLOWED_BUTTON_DESTINATIONS,
    ALLOWED_BUTTON_STYLES,
    ALLOWED_FONTS,
    BLOCKED_ARTWORK_EXTENSIONS,
    BRANDING_STATUSES,
    COLOR_RE,
    IMAGE_SLOTS,
    LIVE_BLOCKING_STATUSES,
    LOGO_IMAGE_EXTENSIONS,
    LOGO_IMAGE_SLOTS,
    WEBSTORES_FEATURE_KEY,
    WEB_IMAGE_EXTENSIONS,
    WHOLE_SECTION_PATHS,
    WebstoreBrandingError,
)
from .webstore_branding_defaults import _deep_merge, _store_type_defaults, default_branding
from .webstore_branding_drafts import (
    _portal_visibility_denied,
    get_portal_branding,
    get_staff_branding,
    save_portal_draft,
    save_staff_draft,
)
from .webstore_branding_publish import (
    _attach_public_asset_urls,
    _collect_image_file_ids,
    _next_published_version,
    _publish_readiness_errors,
    public_branding_asset,
    publish,
    published_branding_for_store,
)
from .webstore_branding_records import (
    _active_assignment,
    _actor_from_identity,
    _actor_from_user,
    _activity,
    _audit,
    _get_store,
    _history,
    _now_iso,
    _record_for_store,
    _require_staff_perm,
    _response,
)
from .webstore_branding_review import owner_approve, owner_request_changes, request_review
from .webstore_branding_validation import (
    _clean_text,
    _content_hash,
    _contrast_ratio,
    _luminance,
    _normalize_image,
    normalize_branding,
    validation_for_branding,
)

__all__ = [
    "ALLOWED_BUTTON_DESTINATIONS",
    "ALLOWED_BUTTON_STYLES",
    "ALLOWED_FONTS",
    "BLOCKED_ARTWORK_EXTENSIONS",
    "BRANDING_STATUSES",
    "COLOR_RE",
    "IMAGE_SLOTS",
    "LIVE_BLOCKING_STATUSES",
    "LOGO_IMAGE_EXTENSIONS",
    "LOGO_IMAGE_SLOTS",
    "WEBSTORES_FEATURE_KEY",
    "WEB_IMAGE_EXTENSIONS",
    "WHOLE_SECTION_PATHS",
    "WebstoreBrandingError",
    "_active_assignment",
    "_activity",
    "_actor_from_identity",
    "_actor_from_user",
    "_attach_public_asset_urls",
    "_audit",
    "_clean_text",
    "_collect_image_file_ids",
    "_content_hash",
    "_contrast_ratio",
    "_deep_merge",
    "_get_store",
    "_history",
    "_luminance",
    "_next_published_version",
    "_normalize_image",
    "_now_iso",
    "_portal_visibility_denied",
    "_publish_readiness_errors",
    "_record_for_store",
    "_require_staff_perm",
    "_response",
    "_store_type_defaults",
    "default_branding",
    "get_portal_branding",
    "get_staff_branding",
    "normalize_branding",
    "owner_approve",
    "owner_request_changes",
    "public_branding_asset",
    "publish",
    "published_branding_for_store",
    "request_review",
    "save_portal_draft",
    "save_staff_draft",
    "validation_for_branding",
]
